apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync
spec:
  vault:
    name: {{.Values.nameKeyVault}} # name of key vault
    object:
      name: {{.Values.nameKeyVaultSecret}} # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: {{.Values.secretKey.name}} # kubernetes secret name
      dataKey: {{.Values.secretKey.key}} # key to store object value in kubernetes secret
